### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by arronqing** [iniself/backtrader_bokeh#1]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python\python3.8.9\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python\python3.8.9\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\project\FuturesTradeFromCTP\venv\lib\site-packages\backtrader_bokeh\live\datahandler.py", line 220, in _t_thread
    data = self._app.generate_data(
  File "<string>", line 540, in generate_data
  File "D:\python\project\FuturesTradeFromCTP\venv\lib\site-packages\backtrader_bokeh\clock.py", line 95, in get_clock_time_at_idx
    return bt.num2date(self._clk.array[idx], self._tz)
  File "D:\python\project\FuturesTradeFromCTP\venv\lib\site-packages\backtrader\utils\dateintern.py", line 165, in num2date
    ix = int(x)
ValueError: cannot convert float NaN to integer

**Comment by iniself** [comment]
check your datafeed
